    - name: Get SentinelOps BuildConfig
      kubernetes.core.k8s_info:
        api_version: build.openshift.io/v1
        kind: BuildConfig
        name: "{{ build_config_name }}"
        namespace: "{{ openshift_namespace }}"
      register: buildconfig
      failed_when: false

    - name: Display BuildConfig API result
      ansible.builtin.debug:
        var: buildconfig
